### ISSUE TITLE
lockup downloading ubuntu

### ISSUE THREAD

**Issue by rminnich** [u-root/webboot#152]
**Describe the bug**
tried to download ubuntu

**To Reproduce**
got to 1105 mb and locked up

**Expected behavior**
did the usb stick run out of space? how do we handle that case? do we need a check to see if it will fit first?

**Additional context**

**Comment by GBA-17** [comment]
The download cancellation feature should let us exit in the case of a lockup.

I think you're right about checking if it fits, though. What if we download the whole ISO to temp, and then try to copy to disk and it throws an error.

**Comment by kellysun878** [comment]
Fixed by #272.
