### ISSUE TITLE
Improve checksum file parsing

### ISSUE THREAD

**Issue by GBA-17** [u-root/webboot#184]
**Describe the bug**
Most checksum files I've encountered use a format like the following:
```
42fd764b3a3544a36d820f4164bb64aa5a6d982073e6d1afdea4853d3858fc98 *linuxmint-20-mate-64bit.iso
```

However, some distros use a slightly different format. One example is Fedora, whose [checksum file](https://getfedora.org/static/checksums/Fedora-Workstation-32-1.6-x86_64-CHECKSUM) is a full PGP-signed message with the line:

```
SHA256 (Fedora-Workstation-Live-x86_64-32-1.6.iso) = 4d0f6653e2e0860c99ffe0ef274a46d875fb85bd2a40cb896dce1ed013566924
```

The checksum file parser in `bootiso.VerifyChecksum()` currently does the following to parse out the checksum value. This method works for most checksum files, but will fail on any distro whose checksum file does not follow the expected format.

1. Grep for line containing the ISO's filename.
2. Split the line and use the 0th element as the checksum value.

**To Reproduce**

1. Open the test checksum file at `pkg/bootiso/testdata/TinyCorePure64.sha256.txt`
2. Change the contents to `SHA256 (TinyCorePure64.iso) = 01ce6b5f4e4f7e98eddc343fc14f1436fb1b0452e6b9f7e07461b6a089a909c1`
3. Run `go test -v` in the directory `pkg/bootiso/`
4. The test `TestChecksum/valid_sha256` will fail

**Expected behavior**
In the case above, the test `TestChecksum/valid_sha256` should pass if we make the change to the checksum file. More generally, the checksum file parser should be able to locate the proper checksum in any checksum file

**Comment by rjoleary** [comment]
Here is a good tutorial on validating the checksum: https://ubuntu.com/tutorials/how-to-verify-ubuntu#1-overview

**Comment by rjoleary** [comment]
We just copied the checksums into the supported distros struct and called it a day.
