### ISSUE TITLE
ISO or script to use webboot binaries?

### ISSUE THREAD

**Issue by guerby** [u-root/webboot#192]
Hi,

I couldn't find an easy way to test webboot as a simple user (not dev) may be I missed an ISO or binary or user oriented web site in the README?

Thanks!

**Comment by orangecms** [comment]
Hi, you can follow the [instructions to build your image](https://github.com/u-root/webboot#usage) and then [put webboot on a USB stick](https://github.com/u-root/webboot#testing-with-a-usb-stick). If you want to check that the image is okay, you can first [test it in QEMU](https://github.com/u-root/webboot#testing-in-qemu).

**Comment by bjakobson** [comment]
@guerby any progress/updates? please let me know what is not working, and also the steps you have taken so far.

**Comment by guerby** [comment]
@bjakobson on debian 10 I did "sudo apt-get install golang", then "go run ." complained: "extraMustBin("iwconfig"): exec: "iwconfig": executable file not found in $PATH". I did "sudo apt-get install wireless-tools", then I did get the same error. debian installs iwconfig in /usr/sbin so it is not in PATH of a non root user. The document mentionned does not say the build process has to be run as root and it's often not a good idea to run builds as root.

Given the two comments I assume the developpers of this project do not want to provide an easy way for non developpers to test webboot at this stage (I'm a dev myself, it's a reasonable early strategy :), so feel free to close this issue.

**Comment by bjakobson** [comment]
@guerby can you paste the output of 'go env'

**Comment by orangecms** [comment]
We haven't fully documented the prerequisites in the README :grimacing: 

See https://github.com/u-root/webboot/blob/master/webboot.go#L6

If you don't need wireless for trying out webboot, you can skip that part and run `go run . --wifi=false`.
