### ISSUE TITLE
Update links to ISO images

### ISSUE THREAD

**Issue by rjoleary** [u-root/webboot#212]
**Describe the bug**
Some links in https://github.com/u-root/webboot/blob/main/cmds/webboot/types.go#L22 no longer point to valid ISO images. It looks like they point to an older version of the ISO which is no longer hosted.

**To Reproduce**

1. For example, if you navigate to this URL: https://sjc.edge.kernel.org/centos/8.2.2004/isos/x86_64/CentOS-8.2.2004-x86_64-minimal.iso, you get "Sorry, we cannot find your kernels"

**Expected behavior**
* The list of ISOs should be updated to their latest version.

**Comment by kellysun878** [comment]
Fixed by #224
