### ISSUE TITLE
"Writing ISO to cache" should print the file path of the cache

### ISSUE THREAD

**Issue by rjoleary** [u-root/webboot#220]
**Describe the bug**
An ISO was downloaded and I do not know where. It would be helpful if the "Writing ISO to cache" message should include the file path the ISO was written to.

**To Reproduce**
Run webboot and download an ISO (for example ubuntu). You will see this message printed in the dialog.

**Expected behavior**
It should instead print "Writing ISO to cache (/tmp/ubuntu.iso)".

**Comment by kellysun878** [comment]
Fixed by #221.
