### ISSUE TITLE
Place a log window on the bottom of the screen

### ISSUE THREAD

**Issue by rjoleary** [u-root/webboot#239]
**Is your feature request related to a problem? Please describe.**
Currently many logs are lost into the void or are printed, but garbled over something else in the UI.

**Describe the solution you'd like**
Instead, there should be a text box in the bottom of the screen to collect the text logs.

**Additional context**
The paragraph widget would probably be the most suitable: https://github.com/gizak/termui/blob/master/widgets/paragraph.go

**Comment by rjoleary** [comment]
For this bug, I am imagining we'll need a new implementation of `io.Writer`. Perhaps a good name would be `TextBoxWriter`.

* The `struct TextBoxWriter { ... }` needs a `func (w *TextBoxWriter) Write` function in order to implement `io.Writer`.
* Since it implements `io.Writer`, it can be used in the https://golang.org/pkg/log/#SetOutput function.
* Whenever any part of the code calls `log.Print`, the `Write` function will be called.
* The `Write` function will use the paragraph widget to `Draw` the text to the screen: https://github.com/gizak/termui/blob/master/widgets/paragraph.go
    * Append the log output to `Text` and call the `Draw` function.
    * Take care to make sure this is thread safe!

**Comment by pgherghetta** [comment]
I'm going to try my idea of saving all log output to a text file that all go files can access. Every time a message like log.Printf is called, the log output will be written to that text file. Finally, menu.go will print out the contents of the text file to the log box.

**Comment by rjoleary** [comment]
This was complete in https://github.com/u-root/webboot/pull/249
