### ISSUE TITLE
wpa_supplicant only connects to wifi when run under strace

### ISSUE THREAD

**Issue by rjoleary** [u-root/webboot#258]
**Describe the bug**
wpa_supplicant is not connecting to wifi. `ip a` prints "state DOWN". It appears something is killing the wpa_supplicant process and causing the connection to deauthorize.

In an attempt to debug this, we ran wpa_supplicant under /usr/bin/strace. Lo and behold, it can connect to wifi when run under strace. As a temporary fix, we now always run wpa_supplicant under strace: https://github.com/u-root/webboot/blob/main/pkg/wifi/iwl.go#L179

**To Reproduce**
Remove the strace from https://github.com/u-root/webboot/blob/main/pkg/wifi/iwl.go#L179. Run `webboot`. Select your wifi essid and password. Connection will timeout.

**Expected behavior**
wpa_supplicant should work without strace. strace is a debug tool.

**Additional context**
We've been debugging this on-and-off for the past month.

**Comment by pgherghetta** [comment]
This issue has been resolved. In iwl.go, we replaced the exec.CommandContext function for wpa supplicant with the exec.Command function instead. This got rid of the need to use the ctx variable in the function which was causing a timeout.
