### ISSUE TITLE
Implementation of wget 

### ISSUE THREAD

**Issue by upatel99** [u-root/webboot#7]
Implementation of it:

Wget command is utilized for downloading files from the internet. My approach to this is to create a separate file inside of the webboot directory that holds the implementations of wget, and then call the wget inside of the webboot command. Louis and I briefly talked about how to combine our parts of the code together at the end. 

As of right now, webboot knows how to handle TinyCore's ISO. Louis has created a map, with the key being the name of the ISO, and the value being the link. This map uses struct that holds the path to find the kernel, initrd, the command line for kexec, and the downloadlink. Since we are trying to get the basic framework working, Louis and I thought to write the wget using the mapping system. In other words, the user, as of right now, should write down "webboot TinyCore". This is where the wget comes in. Wget can check for TinyCore in the map, return an error if it cannot find it with something along the lines of "Sorry, webboot command is currently not applicable with the ISO you asked for". If wget is able to find the name of the ISO inside of the map, then it should take the downloadLink from the struct, and retrieve the ISO with the file name being the same as the map key name found.

**Comment by rminnich** [comment]
why can you not create a wget function inside the webboot package?
func Wget(url string) (io.Reader, error)

you call this and it gives you back an io.Reader you can use to read the data.

look at the wget function in u-root for hints on how to do this.

Also,  having a wget function that looks in a map maintained some other code is not an effective approach. your Wget function should take a URL string and return the io.Reader and nothing more. How the wget is used is part of a different piece of code.

**Comment by upatel99** [comment]
Finished wget :) It does have the functionalities you suggested such as wget taking a URL string and returning an io.ReadCloser and error, having a map as bookmark to supported OSes, and a write function that takes the io.ReadCloser, and writes to a file :)
